disable alpha features (e..g. CronJobs)
k8guard/k8guard-action pull request #20
Opened 2017-08-14 17:52 UTC by boardthatpowder

2017-08-14 18:52 UTC, medyagh requested changes
please add the latest k8guardlibs SHA to the glide yaml, u can grab the latest SHA from https://github.com/k8guard/k8guardlibs/commits/master

2017-08-21 17:36 UTC, boardthatpowder commented
Done, ready for review again.

2017-08-23 16:16 UTC, medyagh approved these changes

2017-08-23 16:16 UTC, medyagh approved these changes

2017-08-23 16:16 UTC, merged